import exerciseIndex from './generated/exercise-index.json';
import type { ExerciseIndexEntry } from './types';

export * from './types';
export * from './media';
export * from './dataset';

/** Slim, bundle-friendly index of all exercises (no instruction text).
 * Generated by `npm run sync-data` — never edit the JSON by hand. */
export const EXERCISE_INDEX = exerciseIndex as ExerciseIndexEntry[];
